# Generated by Django 4.2.11 on 2024-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_content_movie_description_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
