# Generated by Django 4.2.11 on 2024-04-12 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_alter_keyword_name_alter_trend_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.keyword'),
        ),
    ]
